### ISSUE TITLE
Agular 5 ?

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [tithi021/angular6-routing#1]
project is 5 not 6.

  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"

**Comment by tithi021** [comment]
Now Updated. Thanks!
